// project/src/app/zones/helpdesk-zone/helpdesk-dashboard/helpdesk-dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-helpdesk-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    FormsModule
  ],
  template: `
    <div class="dashboard-container">
      <!-- Quick Search Bar -->
      <mat-card class="search-card">
        <mat-card-content>
          <div class="search-section">
            <div class="search-info">
              <h2>Help Desk Control Center</h2>
              <p>Resolve file access issues and support users</p>
            </div>
            
            <div class="search-bar">
              <mat-form-field appearance="outline" class="search-field">
                <mat-label>Search by employee name or file name...</mat-label>
                <input matInput [(ngModel)]="quickSearch" placeholder="Search by employee name or file name...">
                <mat-icon matSuffix>search</mat-icon>
              </mat-form-field>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Stats Grid -->
      <div class="stats-grid">
        <mat-card class="stat-card" *ngFor="let stat of stats">
          <mat-card-content>
            <div class="stat-content">
              <div class="stat-info">
                <p class="stat-label">{{ stat.name }}</p>
                <p class="stat-value">{{ stat.value }}</p>
              </div>
              <mat-icon [style.color]="getStatColor(stat.color)">{{ stat.icon }}</mat-icon>
            </div>
            <div class="stat-change">
              <span [class]="'change-' + stat.changeType">{{ stat.change }}</span>
              <span class="change-period">from yesterday</span>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- Quick Actions -->
      <mat-card class="actions-card">
        <mat-card-header>
          <mat-card-title>Quick Actions</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <div class="actions-grid">
            <button mat-stroked-button class="action-button" *ngFor="let action of quickActions">
              <mat-icon [style.color]="getActionColor(action.color)">{{ action.icon }}</mat-icon>
              <span>{{ action.name }}</span>
            </button>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Dashboard Content -->
      <div class="content-grid">
        <!-- Urgent Issues -->
        <mat-card class="issues-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon style="color: #dc2626;">warning</mat-icon>
              Urgent Issues
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="issues-list">
              <div class="issue-item" *ngFor="let issue of urgentIssues">
                <div class="issue-header">
                  <h4>{{ issue.title }}</h4>
                  <span class="priority-badge" [class]="'priority-' + issue.priority">{{ issue.priority }}</span>
                </div>
                <p class="issue-file">{{ issue.file }}</p>
                <div class="issue-footer">
                  <span class="issue-user">Reported by {{ issue.user }}</span>
                  <span class="issue-time">{{ issue.time }}</span>
                </div>
                <div class="issue-actions">
                  <button mat-button color="primary">Investigate</button>
                  <button mat-button color="accent">Assign</button>
                </div>
              </div>
            </div>
          </mat-card-content>
        </mat-card>

        <!-- Recent Activity -->
        <mat-card class="activity-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon style="color: #059669;">timeline</mat-icon>
              Recent Activity
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="activity-list">
              <div class="activity-item" *ngFor="let activity of recentActivity">
                <div class="activity-indicator" [class]="'indicator-' + activity.status"></div>
                <div class="activity-content">
                  <p class="activity-message">{{ activity.action }}</p>
                  <p class="activity-file">{{ activity.file }}</p>
                  <p class="activity-meta">by {{ activity.user }} • {{ activity.time }}</p>
                </div>
                <span class="activity-status" [class]="'status-' + activity.status">{{ activity.status }}</span>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- System Status -->
      <mat-card class="status-card">
        <mat-card-header>
          <mat-card-title>
            <mat-icon style="color: #059669;">shield</mat-icon>
            System Status
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <div class="status-grid">
            <div class="status-item">
              <div class="status-value">98.7%</div>
              <div class="status-label">System Uptime</div>
            </div>
            <div class="status-item">
              <div class="status-value">1.2s</div>
              <div class="status-label">Avg Response Time</div>
            </div>
            <div class="status-item">
              <div class="status-value">156</div>
              <div class="status-label">Active Users</div>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .dashboard-container {
      display: flex;
      flex-direction: column;
      gap: 24px;
      height: 100%;
    }

    .search-section {
      display: flex;
      flex-direction: column;
      gap: 24px;
    }

    .search-info h2 {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      color: #111827;
    }

    .search-info p {
      margin: 4px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .search-field {
      width: 100%;
      max-width: 600px;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 16px;
    }

    .stat-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
    }

    .stat-label {
      margin: 0;
      font-size: 14px;
      color: #6b7280;
      font-weight: 500;
    }

    .stat-value {
      margin: 8px 0 0 0;
      font-size: 32px;
      font-weight: 700;
      color: #111827;
    }

    .stat-content mat-icon {
      font-size: 32px;
      width: 32px;
      height: 32px;
    }

    .stat-change {
      display: flex;
      align-items: center;
      gap: 4px;
    }

    .change-positive {
      color: #059669;
      font-weight: 600;
    }

    .change-neutral {
      color: #6b7280;
      font-weight: 600;
    }

    .change-period {
      color: #6b7280;
      font-size: 14px;
    }

    .actions-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin-top: 16px;
    }

    .action-button {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 8px;
      padding: 24px;
      height: auto;
      border: 2px solid #e5e7eb;
      transition: all 0.2s;
    }

    .action-button:hover {
      border-color: #059669;
      background-color: #ecfdf5;
    }

    .action-button mat-icon {
      font-size: 32px;
      width: 32px;
      height: 32px;
    }

    .content-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
      flex: 1;
    }

    .issues-list, .activity-list {
      display: flex;
      flex-direction: column;
      gap: 16px;
      margin-top: 16px;
    }

    .issue-item {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      transition: background-color 0.2s;
    }

    .issue-item:hover {
      background-color: #f9fafb;
    }

    .issue-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
    }

    .issue-header h4 {
      margin: 0;
      font-size: 14px;
      font-weight: 600;
      color: #111827;
    }

    .priority-badge {
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
    }

    .priority-urgent {
      background-color: #fef2f2;
      color: #dc2626;
    }

    .priority-high {
      background-color: #fff7ed;
      color: #ea580c;
    }

    .priority-medium {
      background-color: #fefce8;
      color: #ca8a04;
    }

    .issue-file {
      margin: 8px 0;
      font-size: 14px;
      color: #6b7280;
    }

    .issue-footer {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: #6b7280;
      margin-bottom: 12px;
    }

    .issue-actions {
      display: flex;
      gap: 8px;
    }

    .activity-item {
      display: flex;
      align-items: flex-start;
      gap: 12px;
      padding: 12px 0;
      border-bottom: 1px solid #f3f4f6;
    }

    .activity-item:last-child {
      border-bottom: none;
    }

    .activity-indicator {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      margin-top: 6px;
      flex-shrink: 0;
    }

    .indicator-success {
      background-color: #059669;
    }

    .indicator-warning {
      background-color: #d97706;
    }

    .activity-content {
      flex: 1;
    }

    .activity-message {
      margin: 0;
      font-size: 14px;
      color: #111827;
      font-weight: 500;
    }

    .activity-file {
      margin: 2px 0;
      font-size: 14px;
      color: #6b7280;
    }

    .activity-meta {
      margin: 4px 0 0 0;
      font-size: 12px;
      color: #6b7280;
    }

    .activity-status {
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
    }

    .status-success {
      background-color: #ecfdf5;
      color: #059669;
    }

    .status-warning {
      background-color: #fffbeb;
      color: #d97706;
    }

    .status-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 24px;
      margin-top: 16px;
      text-align: center;
    }

    .status-value {
      font-size: 24px;
      font-weight: 700;
      color: #059669;
    }

    .status-label {
      font-size: 14px;
      color: #6b7280;
      margin-top: 4px;
    }

    @media (max-width: 768px) {
      .content-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class HelpDeskDashboardComponent {
  quickSearch = '';

  stats = [
    {
      name: 'Open Tickets',
      value: '12',
      change: '+3',
      changeType: 'neutral',
      icon: 'warning',
      color: 'red'
    },
    {
      name: 'Locked Files',
      value: '8',
      change: '-2',
      changeType: 'positive',
      icon: 'lock',
      color: 'yellow'
    },
    {
      name: 'Emergency Access',
      value: '3',
      change: '+1',
      changeType: 'neutral',
      icon: 'flash_on',
      color: 'orange'
    },
    {
      name: 'Resolved Today',
      value: '24',
      change: '+8',
      changeType: 'positive',
      icon: 'check_circle',
      color: 'green'
    }
  ];

  quickActions = [
    { name: 'Search Files', icon: 'search', color: 'blue' },
    { name: 'Unlock Files', icon: 'lock_open', color: 'yellow' },
    { name: 'Emergency Access', icon: 'flash_on', color: 'red' },
    { name: 'File Recovery', icon: 'restore', color: 'purple' }
  ];

  urgentIssues = [
    {
      title: 'Budget file locked for 2 days',
      user: 'Sarah Wilson',
      file: '/finance/budget-2024.xlsx',
      priority: 'urgent',
      time: '2 hours ago'
    },
    {
      title: 'Cannot access project files',
      user: 'Mike Johnson',
      file: '/projects/alpha/',
      priority: 'high',
      time: '45 minutes ago'
    },
    {
      title: 'Contract file not found',
      user: 'Lisa Chen',
      file: '/contracts/2024-001.pdf',
      priority: 'high',
      time: '1 hour ago'
    }
  ];

  recentActivity = [
    {
      action: 'File unlocked',
      file: 'quarterly-report.xlsx',
      user: 'David Tech',
      time: '5 minutes ago',
      status: 'success'
    },
    {
      action: 'Emergency access granted',
      file: 'client-presentation.pptx',
      user: 'Sarah Support',
      time: '15 minutes ago',
      status: 'warning'
    },
    {
      action: 'File restored',
      file: 'backup-data.xlsx',
      user: 'Mike Helper',
      time: '30 minutes ago',
      status: 'success'
    }
  ];

  getStatColor(color: string): string {
    const colors: { [key: string]: string } = {
      red: '#dc2626',
      yellow: '#d97706',
      orange: '#ea580c',
      green: '#059669',
      blue: '#2563eb',
      purple: '#7c3aed'
    };
    return colors[color] || '#6b7280';
  }

  getActionColor(color: string): string {
    return this.getStatColor(color);
  }
}

// project/src/components/helpdesk/HelpDeskDashboard.tsx
import React, { useState } from 'react';
import { 
  Search, 
  AlertTriangle, 
  Clock, 
  FileText, 
  Users, 
  TrendingUp,
  Activity,
  Lock,
  CheckCircle,
  XCircle,
  Zap,
  Shield
} from 'lucide-react';

const HelpDeskDashboard: React.FC = () => {
  const [quickSearch, setQuickSearch] = useState('');

  const stats = [
    {
      name: 'Open Tickets',
      value: '12',
      change: '+3',
      changeType: 'neutral',
      icon: AlertTriangle,
      color: 'red'
    },
    {
      name: 'Locked Files',
      value: '8',
      change: '-2',
      changeType: 'positive',
      icon: Lock,
      color: 'yellow'
    },
    {
      name: 'Emergency Access',
      value: '3',
      change: '+1',
      changeType: 'neutral',
      icon: Zap,
      color: 'orange'
    },
    {
      name: 'Resolved Today',
      value: '24',
      change: '+8',
      changeType: 'positive',
      icon: CheckCircle,
      color: 'green'
    },
  ];

  const urgentIssues = [
    {
      id: 1,
      type: 'File Locked',
      title: 'Budget file locked for 2 days',
      user: 'Sarah Wilson',
      file: '/finance/budget-2024.xlsx',
      priority: 'urgent',
      time: '2 hours ago'
    },
    {
      id: 2,
      type: 'Access Denied',
      title: 'Cannot access project files',
      user: 'Mike Johnson',
      file: '/projects/alpha/',
      priority: 'high',
      time: '45 minutes ago'
    },
    {
      id: 3,
      type: 'File Missing',
      title: 'Contract file not found',
      user: 'Lisa Chen',
      file: '/contracts/2024-001.pdf',
      priority: 'high',
      time: '1 hour ago'
    }
  ];

  const recentActivity = [
    {
      id: 1,
      action: 'File unlocked',
      file: 'quarterly-report.xlsx',
      user: 'David Tech',
      time: '5 minutes ago',
      status: 'success'
    },
    {
      id: 2,
      action: 'Emergency access granted',
      file: 'client-presentation.pptx',
      user: 'Sarah Support',
      time: '15 minutes ago',
      status: 'warning'
    },
    {
      id: 3,
      action: 'File restored',
      file: 'backup-data.xlsx',
      user: 'Mike Helper',
      time: '30 minutes ago',
      status: 'success'
    }
  ];

  const quickActions = [
    { name: 'Search Files', icon: Search, color: 'blue', action: 'investigation' },
    { name: 'Unlock Files', icon: Lock, color: 'yellow', action: 'locks' },
    { name: 'Emergency Access', icon: Zap, color: 'red', action: 'emergency' },
    { name: 'File Recovery', icon: FileText, color: 'purple', action: 'recovery' }
  ];

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'urgent': return 'text-red-600 bg-red-100';
      case 'high': return 'text-orange-600 bg-orange-100';
      case 'medium': return 'text-yellow-600 bg-yellow-100';
      default: return 'text-green-600 bg-green-100';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'success': return 'text-green-600 bg-green-50';
      case 'warning': return 'text-yellow-600 bg-yellow-50';
      case 'error': return 'text-red-600 bg-red-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  };

  return (
    <div className="space-y-6">
      {/* Quick Search Bar */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Help Desk Control Center</h2>
            <p className="text-sm text-gray-500 mt-1">Resolve file access issues and support users</p>
          </div>
          
          <div className="flex-1 max-w-md lg:ml-8">
            <div className="relative">
              <Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
              <input
                type="text"
                placeholder="Search by employee name or file name..."
                value={quickSearch}
                onChange={(e) => setQuickSearch(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-lg"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <div key={stat.name} className="bg-white rounded-lg shadow-sm p-6 border border-gray-200">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">{stat.name}</p>
                  <p className="text-3xl font-bold text-gray-900 mt-2">{stat.value}</p>
                </div>
                <div className="flex-shrink-0">
                  <Icon className={`h-8 w-8 text-${stat.color}-600`} />
                </div>
              </div>
              <div className="mt-4 flex items-center">
                <span className={`text-sm font-medium ${
                  stat.changeType === 'positive' ? 'text-green-600' :
                  stat.changeType === 'negative' ? 'text-red-600' : 'text-gray-600'
                }`}>
                  {stat.change}
                </span>
                <span className="text-sm text-gray-500 ml-1">from yesterday</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Quick Actions */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-medium text-gray-900 mb-4">Quick Actions</h3>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {quickActions.map((action) => {
            const Icon = action.icon;
            return (
              <button
                key={action.name}
                className={`flex flex-col items-center p-4 rounded-lg border-2 border-${action.color}-200 hover:border-${action.color}-400 hover:bg-${action.color}-50 transition-all duration-200 group`}
              >
                <Icon className={`h-8 w-8 text-${action.color}-600 mb-2 group-hover:scale-110 transition-transform`} />
                <span className="text-sm font-medium text-gray-900">{action.name}</span>
              </button>
            );
          })}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Urgent Issues */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          <div className="px-6 py-4 border-b border-gray-200">
            <h3 className="text-lg font-medium text-gray-900 flex items-center">
              <AlertTriangle className="h-5 w-5 mr-2 text-red-600" />
              Urgent Issues
            </h3>
          </div>
          <div className="p-6">
            <div className="space-y-4">
              {urgentIssues.map((issue) => (
                <div key={issue.id} className="border border-gray-200 rounded-lg p-4 hover:bg-gray-50 transition-colors">
                  <div className="flex items-center justify-between mb-2">
                    <h4 className="text-sm font-medium text-gray-900">{issue.title}</h4>
                    <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getPriorityColor(issue.priority)}`}>
                      {issue.priority}
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mb-2">{issue.file}</p>
                  <div className="flex items-center justify-between text-xs text-gray-500">
                    <span>Reported by {issue.user}</span>
                    <span>{issue.time}</span>
                  </div>
                  <div className="mt-3 flex space-x-2">
                    <button className="text-xs bg-green-600 text-white px-3 py-1 rounded-md hover:bg-green-700 transition-colors">
                      Investigate
                    </button>
                    <button className="text-xs bg-blue-600 text-white px-3 py-1 rounded-md hover:bg-blue-700 transition-colors">
                      Assign
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          <div className="px-6 py-4 border-b border-gray-200">
            <h3 className="text-lg font-medium text-gray-900 flex items-center">
              <Activity className="h-5 w-5 mr-2 text-green-600" />
              Recent Activity
            </h3>
          </div>
          <div className="p-6">
            <div className="space-y-4">
              {recentActivity.map((activity) => (
                <div key={activity.id} className="flex items-start space-x-3">
                  <div className={`flex-shrink-0 w-2 h-2 rounded-full mt-2 ${getStatusColor(activity.status)}`} />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-gray-900 font-medium">{activity.action}</p>
                    <p className="text-sm text-gray-600">{activity.file}</p>
                    <p className="text-xs text-gray-500 mt-1">
                      by {activity.user} • {activity.time}
                    </p>
                  </div>
                  <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(activity.status)}`}>
                    {activity.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* System Status */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-medium text-gray-900 flex items-center">
            <Shield className="h-5 w-5 mr-2 text-green-600" />
            System Status
          </h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="text-2xl font-bold text-green-600">98.7%</div>
              <div className="text-sm text-gray-500">System Uptime</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">1.2s</div>
              <div className="text-sm text-gray-500">Avg Response Time</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-purple-600">156</div>
              <div className="text-sm text-gray-500">Active Users</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HelpDeskDashboard;
