// project/src/components/helpdesk/FileManagement.tsx
import React, { useState } from 'react';
import { 
  Search, 
  FileText, 
  Lock, 
  Unlock, 
  User, 
  Clock,
  AlertTriangle,
  CheckCircle,
  Zap,
  Shield,
  Calendar,
  HardDrive
} from 'lucide-react';
import { format, formatDistanceToNow } from 'date-fns';

const FileManagement: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [selectedFile, setSelectedFile] = useState<any>(null);
  const [showUnlockModal, setShowUnlockModal] = useState(false);
  const [showEmergencyModal, setShowEmergencyModal] = useState(false);
  const [unlockNotes, setUnlockNotes] = useState('');
  const [emergencyReason, setEmergencyReason] = useState('');
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);

  // Mock search results that simulate finding files with similar names
  const getSearchResults = (term: string) => {
    const allFiles = [
      // Budget files example
      {
        id: '1',
        fileName: 'budget-2024.xlsx',
        filePath: '/finance/budget-2024.xlsx',
        isLocked: true,
        lockedBy: { name: 'Mike Johnson', email: 'mike.johnson@company.com', id: 'EMP001' },
        lockDuration: '2 days',
        lockStartTime: new Date('2024-01-13T10:00:00'),
        lastAccessed: new Date('2024-01-13T10:00:00'),
        size: '2.4 MB',
        owner: 'Finance Team',
        location: 'Server: FS-01, Path: /data/finance/',
        department: 'Finance'
      },
      {
        id: '2',
        fileName: 'budget-2024-final.xlsx',
        filePath: '/finance/budget-2024-final.xlsx',
        isLocked: false,
        lockedBy: null,
        lockDuration: null,
        lockStartTime: null,
        lastAccessed: new Date('2024-01-15T14:30:00'),
        size: '2.6 MB',
        owner: 'Finance Team',
        location: 'Server: FS-01, Path: /data/finance/',
        department: 'Finance'
      },
      {
        id: '3',
        fileName: 'budget-2024-backup.xlsx',
        filePath: '/finance/backup/budget-2024-backup.xlsx',
        isLocked: true,
        lockedBy: { name: 'Sarah Wilson', email: 'sarah.wilson@company.com', id: 'EMP002' },
        lockDuration: '4 hours',
        lockStartTime: new Date('2024-01-15T09:00:00'),
        lastAccessed: new Date('2024-01-15T09:00:00'),
        size: '2.3 MB',
        owner: 'Finance Team',
        location: 'Server: FS-02, Path: /backup/finance/',
        department: 'Finance'
      },
      // Contract files example
      {
        id: '4',
        fileName: 'contract-2024-001.pdf',
        filePath: '/legal/contracts/contract-2024-001.pdf',
        isLocked: true,
        lockedBy: { name: 'David Lee', email: 'david.lee@company.com', id: 'EMP003' },
        lockDuration: '1 day',
        lockStartTime: new Date('2024-01-14T15:00:00'),
        lastAccessed: new Date('2024-01-14T15:00:00'),
        size: '1.8 MB',
        owner: 'Legal Team',
        location: 'Server: FS-03, Path: /data/legal/',
        department: 'Legal'
      },
      {
        id: '5',
        fileName: 'contract-template-2024.pdf',
        filePath: '/legal/templates/contract-template-2024.pdf',
        isLocked: false,
        lockedBy: null,
        lockDuration: null,
        lockStartTime: null,
        lastAccessed: new Date('2024-01-15T11:20:00'),
        size: '1.2 MB',
        owner: 'Legal Team',
        location: 'Server: FS-03, Path: /data/legal/templates/',
        department: 'Legal'
      },
      {
        id: '6',
        fileName: 'contract-review-2024.docx',
        filePath: '/legal/reviews/contract-review-2024.docx',
        isLocked: false,
        lockedBy: null,
        lockDuration: null,
        lockStartTime: null,
        lastAccessed: new Date('2024-01-15T16:45:00'),
        size: '890 KB',
        owner: 'Legal Team',
        location: 'Server: FS-03, Path: /data/legal/reviews/',
        department: 'Legal'
      },
      // Employee files example
      {
        id: '7',
        fileName: 'employee-handbook.pdf',
        filePath: '/hr/documents/employee-handbook.pdf',
        isLocked: false,
        lockedBy: null,
        lockDuration: null,
        lockStartTime: null,
        lastAccessed: new Date('2024-01-15T13:15:00'),
        size: '3.2 MB',
        owner: 'HR Team',
        location: 'Server: FS-04, Path: /data/hr/',
        department: 'Human Resources'
      },
      {
        id: '8',
        fileName: 'employee-data-2024.xlsx',
        filePath: '/hr/confidential/employee-data-2024.xlsx',
        isLocked: true,
        lockedBy: { name: 'Lisa Chen', email: 'lisa.chen@company.com', id: 'EMP004' },
        lockDuration: '6 hours',
        lockStartTime: new Date('2024-01-15T08:00:00'),
        lastAccessed: new Date('2024-01-15T08:00:00'),
        size: '4.1 MB',
        owner: 'HR Team',
        location: 'Server: FS-04, Path: /data/hr/confidential/',
        department: 'Human Resources'
      },
      {
        id: '9',
        fileName: 'employee-reviews-q4.docx',
        filePath: '/hr/reviews/employee-reviews-q4.docx',
        isLocked: false,
        lockedBy: null,
        lockDuration: null,
        lockStartTime: null,
        lastAccessed: new Date('2024-01-14T17:30:00'),
        size: '2.7 MB',
        owner: 'HR Team',
        location: 'Server: FS-04, Path: /data/hr/reviews/',
        department: 'Human Resources'
      }
    ];

    // Filter files based on search term
    return allFiles.filter(file =>
      file.fileName.toLowerCase().includes(term.toLowerCase()) ||
      file.filePath.toLowerCase().includes(term.toLowerCase()) ||
      (file.lockedBy && (
        file.lockedBy.name.toLowerCase().includes(term.toLowerCase()) ||
        file.lockedBy.id.toLowerCase().includes(term.toLowerCase())
      ))
    ).slice(0, 3); // Return max 3 results as specified
  };

  const handleSearch = () => {
    if (searchTerm.trim()) {
      const results = getSearchResults(searchTerm.trim());
      setSearchResults(results);
      setHasSearched(true);
      setSelectedFile(null); // Clear selection when new search
    } else {
      setSearchResults([]);
      setHasSearched(false);
    }
  };

  const handleUnlockFile = () => {
    if (!unlockNotes.trim()) return;
    
    // Mock unlock operation
    console.log('Unlocking file:', selectedFile.fileName, 'Notes:', unlockNotes);
    
    // Update the file status
    const updatedFile = {
      ...selectedFile,
      isLocked: false,
      lockedBy: null,
      lockDuration: null,
      lockStartTime: null
    };
    
    setSelectedFile(updatedFile);
    
    // Update search results
    setSearchResults(prev => prev.map(file => 
      file.id === selectedFile.id ? updatedFile : file
    ));
    
    setShowUnlockModal(false);
    setUnlockNotes('');
    setShowSuccessMessage(true);
    
    // Hide success message after 3 seconds
    setTimeout(() => setShowSuccessMessage(false), 3000);
  };

  const handleEmergencyAccess = () => {
    if (!emergencyReason.trim()) return;
    
    console.log('Granting emergency access:', selectedFile.fileName, 'Reason:', emergencyReason);
    setShowEmergencyModal(false);
    setEmergencyReason('');
    setShowSuccessMessage(true);
    
    setTimeout(() => setShowSuccessMessage(false), 3000);
  };

  // Example search suggestions
  const searchExamples = [
    'budget', 'contract', 'employee', 'EMP001', 'Mike Johnson', 'sarah.wilson@company.com'
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div className="space-y-4">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">File Management Center</h2>
            <p className="text-sm text-gray-500 mt-1">Search for files or employees to manage access and resolve issues</p>
          </div>
          
          {/* Unified Search Bar */}
          <div className="space-y-3">
            <div className="flex space-x-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Enter file name/ID or employee name/number..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-lg"
                  onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                />
              </div>
              <button
                onClick={handleSearch}
                className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium"
              >
                Search
              </button>
            </div>
            
            {/* Search Examples */}
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-sm text-gray-500">Try searching for:</span>
              {searchExamples.map((example, index) => (
                <button
                  key={index}
                  onClick={() => {
                    setSearchTerm(example);
                    const results = getSearchResults(example);
                    setSearchResults(results);
                    setHasSearched(true);
                    setSelectedFile(null);
                  }}
                  className="px-2 py-1 text-xs bg-gray-100 text-gray-600 rounded hover:bg-gray-200 transition-colors"
                >
                  {example}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Success Message */}
      {showSuccessMessage && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <div className="flex items-center">
            <CheckCircle className="h-5 w-5 text-green-600 mr-2" />
            <span className="text-green-800 font-medium">
              Operation completed successfully! File status has been updated.
            </span>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Search Results */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium text-gray-900">
                Search Results
                {searchResults.length > 0 && (
                  <span className="ml-2 text-sm text-gray-500">({searchResults.length} found)</span>
                )}
              </h3>
            </div>
            <div className="divide-y divide-gray-200 max-h-96 overflow-y-auto">
              {!hasSearched ? (
                <div className="p-6 text-center text-gray-500">
                  <Search className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                  <p className="font-medium mb-2">Ready to search</p>
                  <p className="text-sm">Enter a file name, employee name, or ID to get started</p>
                </div>
              ) : searchResults.length === 0 ? (
                <div className="p-6 text-center text-gray-500">
                  <Search className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                  <p className="font-medium mb-2">No results found</p>
                  <p className="text-sm">Try a different search term or check the spelling</p>
                </div>
              ) : (
                searchResults.map((file) => (
                  <div
                    key={file.id}
                    onClick={() => setSelectedFile(file)}
                    className={`p-4 cursor-pointer hover:bg-gray-50 transition-colors ${
                      selectedFile?.id === file.id ? 'bg-green-50 border-r-2 border-green-600' : ''
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <FileText className="h-8 w-8 text-green-600" />
                        <div>
                          <h4 className="font-medium text-gray-900">{file.fileName}</h4>
                          <p className="text-sm text-gray-500 truncate max-w-xs">{file.filePath}</p>
                          <div className="flex items-center space-x-2 mt-1">
                            <span className="text-xs text-gray-400">{file.size}</span>
                            <span className="text-xs text-gray-400">•</span>
                            <span className="text-xs text-gray-400">{file.department}</span>
                          </div>
                        </div>
                      </div>
                      <div className="flex flex-col items-end space-y-1">
                        {file.isLocked ? (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-red-100 text-red-800">
                            <Lock className="h-3 w-3 mr-1" />
                            Locked
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800">
                            <Unlock className="h-3 w-3 mr-1" />
                            Available
                          </span>
                        )}
                        {file.lockDuration && (
                          <span className="text-xs text-gray-500">{file.lockDuration}</span>
                        )}
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* File Details and Actions */}
        <div className="lg:col-span-2">
          {selectedFile ? (
            <div className="space-y-6">
              {/* File Overview */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <div className="flex items-start justify-between">
                  <div className="flex items-center space-x-4">
                    <FileText className="h-16 w-16 text-green-600" />
                    <div>
                      <h3 className="text-xl font-semibold text-gray-900">{selectedFile.fileName}</h3>
                      <p className="text-gray-600 mt-1">{selectedFile.filePath}</p>
                      <div className="mt-3 grid grid-cols-2 gap-4 text-sm">
                        <div>
                          <span className="text-gray-500">Size:</span>
                          <span className="ml-1 text-gray-900">{selectedFile.size}</span>
                        </div>
                        <div>
                          <span className="text-gray-500">Owner:</span>
                          <span className="ml-1 text-gray-900">{selectedFile.owner}</span>
                        </div>
                        <div>
                          <span className="text-gray-500">Department:</span>
                          <span className="ml-1 text-gray-900">{selectedFile.department}</span>
                        </div>
                        <div>
                          <span className="text-gray-500">Last accessed:</span>
                          <span className="ml-1 text-gray-900">{formatDistanceToNow(selectedFile.lastAccessed)} ago</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center space-x-2">
                    {selectedFile.isLocked ? (
                      <span className="inline-flex items-center px-3 py-2 rounded-full text-sm font-medium bg-red-100 text-red-800">
                        <Lock className="h-4 w-4 mr-2" />
                        File Locked
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-3 py-2 rounded-full text-sm font-medium bg-green-100 text-green-800">
                        <CheckCircle className="h-4 w-4 mr-2" />
                        Available
                      </span>
                    )}
                  </div>
                </div>

                {/* File Location */}
                <div className="mt-4 p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center">
                    <HardDrive className="h-4 w-4 text-gray-500 mr-2" />
                    <span className="text-sm font-medium text-gray-700">Storage Location:</span>
                  </div>
                  <p className="text-sm text-gray-600 mt-1 font-mono">{selectedFile.location}</p>
                </div>

                {selectedFile.isLocked && selectedFile.lockedBy && (
                  <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                    <div className="flex items-start">
                      <AlertTriangle className="h-5 w-5 text-yellow-600 mr-3 mt-0.5" />
                      <div className="flex-1">
                        <p className="text-sm font-medium text-yellow-800">
                          File locked by {selectedFile.lockedBy.name}
                        </p>
                        <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-2 text-sm text-yellow-700">
                          <div>
                            <span className="font-medium">Email:</span> {selectedFile.lockedBy.email}
                          </div>
                          <div>
                            <span className="font-medium">Employee ID:</span> {selectedFile.lockedBy.id}
                          </div>
                          <div>
                            <span className="font-medium">Lock Duration:</span> {selectedFile.lockDuration}
                          </div>
                          <div>
                            <span className="font-medium">Locked Since:</span> {format(selectedFile.lockStartTime, 'MMM d, HH:mm')}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Action Menu */}
              <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                <h4 className="font-medium text-gray-900 mb-4 flex items-center">
                  <Shield className="h-5 w-5 mr-2 text-green-600" />
                  Available Actions
                </h4>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {selectedFile.isLocked ? (
                    <button
                      onClick={() => setShowUnlockModal(true)}
                      className="flex items-center justify-center space-x-2 p-4 border-2 border-red-200 rounded-lg hover:border-red-400 hover:bg-red-50 transition-all duration-200 group"
                    >
                      <Unlock className="h-6 w-6 text-red-600 group-hover:scale-110 transition-transform" />
                      <span className="font-medium text-gray-900">Unlock File</span>
                    </button>
                  ) : (
                    <div className="flex items-center justify-center space-x-2 p-4 border-2 border-gray-200 rounded-lg bg-gray-50 cursor-not-allowed">
                      <CheckCircle className="h-6 w-6 text-gray-400" />
                      <span className="font-medium text-gray-500">File Available</span>
                    </div>
                  )}
                  
                  <button
                    onClick={() => setShowEmergencyModal(true)}
                    className="flex items-center justify-center space-x-2 p-4 border-2 border-orange-200 rounded-lg hover:border-orange-400 hover:bg-orange-50 transition-all duration-200 group"
                  >
                    <Zap className="h-6 w-6 text-orange-600 group-hover:scale-110 transition-transform" />
                    <span className="font-medium text-gray-900">Grant Emergency Access</span>
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-12 text-center">
              <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">Select a file to manage</h3>
              <p className="text-gray-500">Choose a file from the search results to view details and available actions</p>
              {hasSearched && searchResults.length > 0 && (
                <p className="text-sm text-green-600 mt-2">
                  {searchResults.length} file{searchResults.length !== 1 ? 's' : ''} found - click on one to get started
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Unlock File Modal */}
      {showUnlockModal && selectedFile && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium text-gray-900 flex items-center">
                <Unlock className="h-5 w-5 text-red-500 mr-2" />
                Unlock File
              </h3>
            </div>
            <div className="px-6 py-4 space-y-4">
              <div className="bg-yellow-50 border border-yellow-200 rounded-md p-4">
                <p className="text-sm text-yellow-800">
                  <strong>Warning:</strong> Unlocking this file will notify the current user and may interrupt their work.
                </p>
              </div>
              
              <div>
                <label className="text-sm font-medium text-gray-500">File</label>
                <p className="text-sm text-gray-900">{selectedFile.fileName}</p>
              </div>
              
              <div>
                <label className="text-sm font-medium text-gray-500">Currently Locked By</label>
                <p className="text-sm text-gray-900">{selectedFile.lockedBy?.name} ({selectedFile.lockedBy?.id})</p>
              </div>
              
              <div>
                <label className="text-sm font-medium text-gray-700">Notes for Unlocking *</label>
                <textarea
                  value={unlockNotes}
                  onChange={(e) => setUnlockNotes(e.target.value)}
                  rows={3}
                  className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:ring-2 focus:ring-green-500 focus:border-green-500"
                  placeholder="Explain why this file needs to be unlocked..."
                  required
                />
              </div>
            </div>
            <div className="px-6 py-4 border-t border-gray-200 flex justify-end space-x-3">
              <button
                onClick={() => setShowUnlockModal(false)}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleUnlockFile}
                disabled={!unlockNotes.trim()}
                className="px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-md hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Confirm Unlock
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Emergency Access Modal */}
      {showEmergencyModal && selectedFile && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full">
            <div className="px-6 py-4 border-b border-gray-200">
              <h3 className="text-lg font-medium text-gray-900 flex items-center">
                <Zap className="h-5 w-5 text-orange-500 mr-2" />
                Grant Emergency Access
              </h3>
            </div>
            <div className="px-6 py-4 space-y-4">
              <div className="bg-orange-50 border border-orange-200 rounded-md p-4">
                <p className="text-sm text-orange-800">
                  <strong>Emergency Access:</strong> This will grant temporary 24-hour access that bypasses normal approval processes.
                </p>
              </div>
              
              <div>
                <label className="text-sm font-medium text-gray-500">File</label>
                <p className="text-sm text-gray-900">{selectedFile.fileName}</p>
              </div>
              
              <div>
                <label className="text-sm font-medium text-gray-700">Business Justification *</label>
                <textarea
                  value={emergencyReason}
                  onChange={(e) => setEmergencyReason(e.target.value)}
                  rows={3}
                  className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:ring-2 focus:ring-orange-500 focus:border-orange-500"
                  placeholder="Explain the urgent business need for emergency access..."
                  required
                />
              </div>
            </div>
            <div className="px-6 py-4 border-t border-gray-200 flex justify-end space-x-3">
              <button
                onClick={() => setShowEmergencyModal(false)}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleEmergencyAccess}
                disabled={!emergencyReason.trim()}
                className="px-4 py-2 text-sm font-medium text-white bg-orange-600 rounded-md hover:bg-orange-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Grant Access
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FileManagement;

// project/src/app/zones/helpdesk-zone/file-management/file-management.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import { FormsModule } from '@angular/forms';
import { FileService } from '../../../services/file.service';
import { FileInfo } from '../../../models/file.model';
import { UnlockFileDialogComponent } from './unlock-file-dialog.component';
import { EmergencyAccessDialogComponent } from './emergency-access-dialog.component';

@Component({
  selector: 'app-file-management',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatSnackBarModule,
    FormsModule,
    UnlockFileDialogComponent,
    EmergencyAccessDialogComponent
  ],
  template: `
    <div class="file-management-container">
      <!-- Header -->
      <mat-card class="header-card">
        <mat-card-content>
          <div class="header-content">
            <div class="header-info">
              <h2>File Management Center</h2>
              <p>Search for files or employees to manage access and resolve issues</p>
            </div>
          </div>
          
          <!-- Search Bar -->
          <div class="search-section">
            <div class="search-bar">
              <mat-form-field appearance="outline" class="search-field">
                <mat-label>Enter file name/ID or employee name/number...</mat-label>
                <input matInput [(ngModel)]="searchTerm" (keyup.enter)="handleSearch()" placeholder="Enter file name/ID or employee name/number...">
                <mat-icon matSuffix>search</mat-icon>
              </mat-form-field>
              <button mat-raised-button color="primary" (click)="handleSearch()" [disabled]="isLoading">
                Search
              </button>
            </div>
            
            <!-- Search Examples -->
            <div class="search-examples">
              <span class="examples-label">Try searching for:</span>
              <button 
                *ngFor="let example of searchExamples" 
                class="search-example"
                (click)="searchExample(example)">
                {{ example }}
              </button>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Success Message -->
      <div *ngIf="showSuccessMessage" class="success-message">
        <mat-icon>check_circle</mat-icon>
        <span>Operation completed successfully! File status has been updated.</span>
      </div>

      <!-- Content Grid -->
      <div class="content-grid">
        <!-- Search Results -->
        <div class="results-section">
          <mat-card class="results-card">
            <mat-card-header>
              <mat-card-title>
                Search Results
                <span *ngIf="searchResults.length > 0" class="results-count">({{ searchResults.length }} found)</span>
              </mat-card-title>
            </mat-card-header>
            <mat-card-content>
              <div class="results-content">
                <!-- Loading State -->
                <div *ngIf="isLoading" class="loading-state">
                  <mat-icon>hourglass_empty</mat-icon>
                  <p>Searching...</p>
                </div>

                <!-- No Search State -->
                <div *ngIf="!hasSearched && !isLoading" class="empty-state">
                  <mat-icon>search</mat-icon>
                  <p class="empty-title">Ready to search</p>
                  <p class="empty-subtitle">Enter a file name, employee name, or ID to get started</p>
                </div>

                <!-- No Results State -->
                <div *ngIf="hasSearched && searchResults.length === 0 && !isLoading" class="empty-state">
                  <mat-icon>search_off</mat-icon>
                  <p class="empty-title">No results found</p>
                  <p class="empty-subtitle">Try a different search term or check the spelling</p>
                </div>

                <!-- Results List -->
                <div *ngIf="searchResults.length > 0" class="results-list">
                  <div 
                    *ngFor="let file of searchResults" 
                    class="result-item"
                    [class.selected]="selectedFile?.id === file.id"
                    (click)="selectFile(file)">
                    <div class="file-icon">
                      <mat-icon>description</mat-icon>
                    </div>
                    <div class="file-info">
                      <h4>{{ file.fileName }}</h4>
                      <p class="file-path">{{ file.filePath }}</p>
                      <div class="file-meta">
                        <span>{{ file.size }}</span>
                        <span>•</span>
                        <span>{{ file.department }}</span>
                      </div>
                    </div>
                    <div class="file-status">
                      <div *ngIf="file.isLocked" class="status-badge locked">
                        <mat-icon>lock</mat-icon>
                        Locked
                      </div>
                      <div *ngIf="!file.isLocked" class="status-badge available">
                        <mat-icon>lock_open</mat-icon>
                        Available
                      </div>
                      <div *ngIf="file.lockDuration" class="lock-duration">{{ file.lockDuration }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </mat-card-content>
          </mat-card>
        </div>

        <!-- File Details -->
        <div class="details-section">
          <mat-card *ngIf="selectedFile" class="details-card">
            <!-- File Overview -->
            <mat-card-header>
              <div class="file-header">
                <mat-icon class="file-icon-large">description</mat-icon>
                <div class="file-title">
                  <h3>{{ selectedFile.fileName }}</h3>
                  <p>{{ selectedFile.filePath }}</p>
                </div>
                <div class="file-status-large">
                  <div *ngIf="selectedFile.isLocked" class="status-badge locked large">
                    <mat-icon>lock</mat-icon>
                    File Locked
                  </div>
                  <div *ngIf="!selectedFile.isLocked" class="status-badge available large">
                    <mat-icon>check_circle</mat-icon>
                    Available
                  </div>
                </div>
              </div>
            </mat-card-header>

            <mat-card-content>
              <!-- File Details -->
              <div class="file-details">
                <div class="detail-grid">
                  <div class="detail-item">
                    <span class="detail-label">Size:</span>
                    <span class="detail-value">{{ selectedFile.size }}</span>
                  </div>
                  <div class="detail-item">
                    <span class="detail-label">Owner:</span>
                    <span class="detail-value">{{ selectedFile.owner }}</span>
                  </div>
                  <div class="detail-item">
                    <span class="detail-label">Department:</span>
                    <span class="detail-value">{{ selectedFile.department }}</span>
                  </div>
                  <div class="detail-item">
                    <span class="detail-label">Last accessed:</span>
                    <span class="detail-value">{{ getTimeAgo(selectedFile.lastAccessed) }}</span>
                  </div>
                </div>

                <!-- Storage Location -->
                <div class="location-info">
                  <div class="location-header">
                    <mat-icon>storage</mat-icon>
                    <span>Storage Location:</span>
                  </div>
                  <p class="location-path">{{ selectedFile.location }}</p>
                </div>

                <!-- Lock Information -->
                <div *ngIf="selectedFile.isLocked && selectedFile.lockedBy" class="lock-info">
                  <div class="lock-warning">
                    <mat-icon>warning</mat-icon>
                    <div class="lock-details">
                      <p class="lock-title">File locked by {{ selectedFile.lockedBy.name }}</p>
                      <div class="lock-meta">
                        <div class="lock-meta-item">
                          <span class="meta-label">Email:</span>
                          <span>{{ selectedFile.lockedBy.email }}</span>
                        </div>
                        <div class="lock-meta-item">
                          <span class="meta-label">Employee ID:</span>
                          <span>{{ selectedFile.lockedBy.id }}</span>
                        </div>
                        <div class="lock-meta-item">
                          <span class="meta-label">Lock Duration:</span>
                          <span>{{ selectedFile.lockDuration }}</span>
                        </div>
                        <div class="lock-meta-item">
                          <span class="meta-label">Locked Since:</span>
                          <span>{{ formatDate(selectedFile.lockStartTime) }}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Action Menu -->
              <div class="action-menu">
                <h4>
                  <mat-icon>shield</mat-icon>
                  Available Actions
                </h4>
                
                <div class="actions-grid">
                  <button 
                    *ngIf="selectedFile.isLocked"
                    mat-stroked-button 
                    class="action-button unlock"
                    (click)="openUnlockDialog()">
                    <mat-icon>lock_open</mat-icon>
                    <span>Unlock File</span>
                  </button>
                  
                  <button 
                    *ngIf="!selectedFile.isLocked"
                    mat-stroked-button 
                    class="action-button disabled"
                    disabled>
                    <mat-icon>check_circle</mat-icon>
                    <span>File Available</span>
                  </button>
                  
                  <button 
                    mat-stroked-button 
                    class="action-button emergency"
                    (click)="openEmergencyDialog()">
                    <mat-icon>flash_on</mat-icon>
                    <span>Grant Emergency Access</span>
                  </button>
                </div>
              </div>
            </mat-card-content>
          </mat-card>

          <!-- No Selection State -->
          <mat-card *ngIf="!selectedFile" class="no-selection-card">
            <mat-card-content>
              <div class="no-selection-content">
                <mat-icon>description</mat-icon>
                <h3>Select a file to manage</h3>
                <p>Choose a file from the search results to view details and available actions</p>
                <p *ngIf="hasSearched && searchResults.length > 0" class="search-hint">
                  {{ searchResults.length }} file{{ searchResults.length !== 1 ? 's' : '' }} found - click on one to get started
                </p>
              </div>
            </mat-card-content>
          </mat-card>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .file-management-container {
      display: flex;
      flex-direction: column;
      gap: 24px;
      height: 100%;
    }

    .header-content {
      margin-bottom: 24px;
    }

    .header-info h2 {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      color: #111827;
    }

    .header-info p {
      margin: 4px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .search-section {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .search-bar {
      display: flex;
      gap: 16px;
      align-items: center;
    }

    .search-field {
      flex: 1;
      max-width: 600px;
    }

    .search-examples {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 8px;
    }

    .examples-label {
      font-size: 14px;
      color: #6b7280;
    }

    .search-example {
      padding: 4px 8px;
      background-color: #f3f4f6;
      color: #6b7280;
      border: none;
      border-radius: 4px;
      font-size: 12px;
      cursor: pointer;
      transition: background-color 0.2s;
    }

    .search-example:hover {
      background-color: #e5e7eb;
    }

    .success-message {
      background-color: #d1fae5;
      border: 1px solid #a7f3d0;
      color: #065f46;
      padding: 12px;
      border-radius: 8px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .content-grid {
      display: grid;
      grid-template-columns: 1fr 2fr;
      gap: 24px;
      flex: 1;
      min-height: 0;
    }

    .results-card, .details-card, .no-selection-card {
      height: fit-content;
      max-height: 600px;
    }

    .results-content {
      max-height: 500px;
      overflow-y: auto;
    }

    .loading-state, .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 48px 24px;
      text-align: center;
    }

    .loading-state mat-icon, .empty-state mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      color: #d1d5db;
      margin-bottom: 16px;
    }

    .empty-title {
      margin: 0;
      font-weight: 600;
      color: #111827;
      font-size: 16px;
    }

    .empty-subtitle {
      margin: 8px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .results-count {
      font-size: 14px;
      color: #6b7280;
      font-weight: normal;
    }

    .results-list {
      display: flex;
      flex-direction: column;
      gap: 1px;
    }

    .result-item {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 16px;
      cursor: pointer;
      transition: background-color 0.2s;
      border-radius: 8px;
    }

    .result-item:hover {
      background-color: #f9fafb;
    }

    .result-item.selected {
      background-color: #ecfdf5;
      border: 2px solid #059669;
    }

    .file-icon mat-icon {
      font-size: 32px;
      width: 32px;
      height: 32px;
      color: #059669;
    }

    .file-info {
      flex: 1;
    }

    .file-info h4 {
      margin: 0;
      font-weight: 600;
      color: #111827;
      font-size: 14px;
    }

    .file-path {
      margin: 2px 0;
      color: #6b7280;
      font-size: 12px;
      max-width: 200px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .file-meta {
      display: flex;
      align-items: center;
      gap: 4px;
      font-size: 12px;
      color: #6b7280;
      margin-top: 4px;
    }

    .file-status {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 4px;
    }

    .status-badge {
      display: flex;
      align-items: center;
      gap: 4px;
      padding: 4px 8px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
    }

    .status-badge.locked {
      background-color: #fef2f2;
      color: #dc2626;
    }

    .status-badge.available {
      background-color: #ecfdf5;
      color: #059669;
    }

    .status-badge.large {
      padding: 8px 16px;
      font-size: 14px;
    }

    .status-badge mat-icon {
      font-size: 16px;
      width: 16px;
      height: 16px;
    }

    .lock-duration {
      font-size: 12px;
      color: #6b7280;
    }

    .file-header {
      display: flex;
      align-items: flex-start;
      gap: 16px;
      width: 100%;
    }

    .file-icon-large {
      font-size: 64px;
      width: 64px;
      height: 64px;
      color: #059669;
    }

    .file-title {
      flex: 1;
    }

    .file-title h3 {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      color: #111827;
    }

    .file-title p {
      margin: 4px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .file-details {
      margin-top: 24px;
    }

    .detail-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
      margin-bottom: 24px;
    }

    .detail-item {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .detail-label {
      font-size: 14px;
      color: #6b7280;
      font-weight: 500;
    }

    .detail-value {
      font-size: 14px;
      color: #111827;
    }

    .location-info {
      background-color: #f9fafb;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 24px;
    }

    .location-header {
      display: flex;
      align-items: center;
      gap: 8px;
      font-weight: 600;
      color: #374151;
      margin-bottom: 8px;
    }

    .location-path {
      margin: 0;
      font-family: monospace;
      font-size: 14px;
      color: #6b7280;
    }

    .lock-info {
      margin-bottom: 24px;
    }

    .lock-warning {
      background-color: #fffbeb;
      border: 1px solid #fed7aa;
      border-radius: 8px;
      padding: 16px;
      display: flex;
      align-items: flex-start;
      gap: 12px;
    }

    .lock-warning mat-icon {
      color: #d97706;
      margin-top: 2px;
    }

    .lock-title {
      margin: 0 0 12px 0;
      font-weight: 600;
      color: #92400e;
    }

    .lock-meta {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
    }

    .lock-meta-item {
      display: flex;
      gap: 4px;
      font-size: 14px;
    }

    .meta-label {
      font-weight: 600;
      color: #78350f;
    }

    .action-menu {
      border-top: 1px solid #e5e7eb;
      padding-top: 24px;
    }

    .action-menu h4 {
      margin: 0 0 16px 0;
      font-size: 16px;
      font-weight: 600;
      color: #111827;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .actions-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }

    .action-button {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 8px;
      padding: 24px;
      height: auto;
      border: 2px solid;
      transition: all 0.2s;
    }

    .action-button.unlock {
      border-color: #fecaca;
      color: #dc2626;
    }

    .action-button.unlock:hover:not(:disabled) {
      border-color: #dc2626;
      background-color: #fef2f2;
    }

    .action-button.emergency {
      border-color: #fed7aa;
      color: #ea580c;
    }

    .action-button.emergency:hover:not(:disabled) {
      border-color: #ea580c;
      background-color: #fff7ed;
    }

    .action-button.disabled {
      border-color: #e5e7eb;
      color: #9ca3af;
      cursor: not-allowed;
    }

    .action-button mat-icon {
      font-size: 24px;
      width: 24px;
      height: 24px;
    }

    .no-selection-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 48px 24px;
      text-align: center;
    }

    .no-selection-content mat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      color: #d1d5db;
      margin-bottom: 16px;
    }

    .no-selection-content h3 {
      margin: 0;
      font-size: 18px;
      font-weight: 600;
      color: #111827;
    }

    .no-selection-content p {
      margin: 8px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .search-hint {
      color: #059669 !important;
      font-weight: 500;
    }

    @media (max-width: 768px) {
      .content-grid {
        grid-template-columns: 1fr;
      }
      
      .detail-grid {
        grid-template-columns: 1fr;
      }
      
      .lock-meta {
        grid-template-columns: 1fr;
      }
      
      .actions-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class FileManagementComponent implements OnInit {
  searchTerm = '';
  searchResults: FileInfo[] = [];
  selectedFile: FileInfo | null = null;
  isLoading = false;
  hasSearched = false;
  showSuccessMessage = false;

  searchExamples = [
    'budget', 'contract', 'employee', 'EMP001', 'Mike Johnson', 'sarah.wilson@company.com'
  ];

  constructor(
    private fileService: FileService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar
  ) {}

  ngOnInit() {}

  handleSearch() {
    if (!this.searchTerm.trim()) return;

    this.isLoading = true;
    this.hasSearched = true;
    this.selectedFile = null;

    this.fileService.searchFiles(this.searchTerm.trim()).subscribe({
      next: (results) => {
        this.searchResults = results;
        this.isLoading = false;
      },
      error: (error) => {
        console.error('Search error:', error);
        this.isLoading = false;
        this.snackBar.open('Search failed. Please try again.', 'Close', { duration: 3000 });
      }
    });
  }

  searchExample(example: string) {
    this.searchTerm = example;
    this.handleSearch();
  }

  selectFile(file: FileInfo) {
    this.selectedFile = file;
  }

  openUnlockDialog() {
    if (!this.selectedFile) return;

    const dialogRef = this.dialog.open(UnlockFileDialogComponent, {
      width: '500px',
      data: { file: this.selectedFile }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.fileService.unlockFile(this.selectedFile!.id, result.notes).subscribe({
          next: () => {
            // Update file status
            this.selectedFile!.isLocked = false;
            this.selectedFile!.lockedBy = undefined;
            this.selectedFile!.lockDuration = undefined;
            this.selectedFile!.lockStartTime = undefined;

            // Update search results
            const index = this.searchResults.findIndex(f => f.id === this.selectedFile!.id);
            if (index !== -1) {
              this.searchResults[index] = { ...this.selectedFile! };
            }

            this.showSuccessMessage = true;
            setTimeout(() => this.showSuccessMessage = false, 3000);
          },
          error: (error) => {
            console.error('Unlock error:', error);
            this.snackBar.open('Failed to unlock file. Please try again.', 'Close', { duration: 3000 });
          }
        });
      }
    });
  }

  openEmergencyDialog() {
    if (!this.selectedFile) return;

    const dialogRef = this.dialog.open(EmergencyAccessDialogComponent, {
      width: '500px',
      data: { file: this.selectedFile }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.fileService.grantEmergencyAccess(this.selectedFile!.id, result.reason).subscribe({
          next: () => {
            this.showSuccessMessage = true;
            setTimeout(() => this.showSuccessMessage = false, 3000);
          },
          error: (error) => {
            console.error('Emergency access error:', error);
            this.snackBar.open('Failed to grant emergency access. Please try again.', 'Close', { duration: 3000 });
          }
        });
      }
    });
  }

  getTimeAgo(date: Date): string {
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffHours / 24);

    if (diffDays > 0) {
      return `${diffDays} day${diffDays > 1 ? 's' : ''} ago`;
    } else if (diffHours > 0) {
      return `${diffHours} hour${diffHours > 1 ? 's' : ''} ago`;
    } else {
      return 'Less than an hour ago';
    }
  }

  formatDate(date: Date | undefined): string {
    if (!date) return 'Unknown';
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date);
  }
}
