// project/src/components/admin/AdminSettings.tsx
import React, { useState } from 'react';
import { 
  Settings, 
  Shield, 
  Clock, 
  Database, 
  Bell,
  Save,
  RefreshCw,
  AlertTriangle
} from 'lucide-react';

const AdminSettings: React.FC = () => {
  const [settings, setSettings] = useState({
    // Security Settings
    passwordMinLength: 8,
    passwordRequireSpecialChars: true,
    sessionTimeout: 30,
    maxLoginAttempts: 5,
    
    // File Lock Settings
    defaultLockDuration: 60,
    maxLockDuration: 480,
    autoReleaseStuckLocks: true,
    stuckLockThreshold: 120,
    
    // Emergency Access Settings
    emergencyAccessMaxDuration: 24,
    emergencyAccessRequireApproval: true,
    emergencyAccessNotifyOwner: true,
    
    // System Settings
    auditLogRetention: 90,
    backupFrequency: 'daily',
    maintenanceWindow: '02:00',
    
    // Notification Settings
    emailNotifications: true,
    slackIntegration: false,
    smsAlerts: false
  });

  const handleSave = () => {
    console.log('Saving settings:', settings);
    // Mock save implementation
  };

  const handleReset = () => {
    // Reset to defaults
    console.log('Resetting to defaults');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">System Settings</h2>
            <p className="text-sm text-gray-500 mt-1">Configure system-wide settings and policies</p>
          </div>
          <div className="flex space-x-3">
            <button
              onClick={handleReset}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 transition-colors"
            >
              <RefreshCw className="h-4 w-4" />
              <span>Reset</span>
            </button>
            <button
              onClick={handleSave}
              className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              <Save className="h-4 w-4" />
              <span>Save Changes</span>
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Security Settings */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <Shield className="h-5 w-5 mr-2 text-blue-600" />
            Security Settings
          </h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Minimum Password Length
              </label>
              <input
                type="number"
                value={settings.passwordMinLength}
                onChange={(e) => setSettings({...settings, passwordMinLength: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                min="6"
                max="20"
              />
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={settings.passwordRequireSpecialChars}
                onChange={(e) => setSettings({...settings, passwordRequireSpecialChars: e.target.checked})}
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <label className="ml-2 text-sm text-gray-700">
                Require special characters in passwords
              </label>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Session Timeout (minutes)
              </label>
              <input
                type="number"
                value={settings.sessionTimeout}
                onChange={(e) => setSettings({...settings, sessionTimeout: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                min="5"
                max="480"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Max Login Attempts
              </label>
              <input
                type="number"
                value={settings.maxLoginAttempts}
                onChange={(e) => setSettings({...settings, maxLoginAttempts: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                min="3"
                max="10"
              />
            </div>
          </div>
        </div>

        {/* File Lock Settings */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <Clock className="h-5 w-5 mr-2 text-green-600" />
            File Lock Settings
          </h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Default Lock Duration (minutes)
              </label>
              <input
                type="number"
                value={settings.defaultLockDuration}
                onChange={(e) => setSettings({...settings, defaultLockDuration: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-green-500 focus:border-green-500"
                min="15"
                max="480"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Maximum Lock Duration (minutes)
              </label>
              <input
                type="number"
                value={settings.maxLockDuration}
                onChange={(e) => setSettings({...settings, maxLockDuration: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-green-500 focus:border-green-500"
                min="60"
                max="1440"
              />
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={settings.autoReleaseStuckLocks}
                onChange={(e) => setSettings({...settings, autoReleaseStuckLocks: e.target.checked})}
                className="h-4 w-4 text-green-600 focus:ring-green-500 border-gray-300 rounded"
              />
              <label className="ml-2 text-sm text-gray-700">
                Auto-release stuck locks
              </label>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Stuck Lock Threshold (minutes)
              </label>
              <input
                type="number"
                value={settings.stuckLockThreshold}
                onChange={(e) => setSettings({...settings, stuckLockThreshold: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-green-500 focus:border-green-500"
                min="30"
                max="480"
              />
            </div>
          </div>
        </div>

        {/* Emergency Access Settings */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <AlertTriangle className="h-5 w-5 mr-2 text-orange-600" />
            Emergency Access Settings
          </h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Maximum Emergency Access Duration (hours)
              </label>
              <input
                type="number"
                value={settings.emergencyAccessMaxDuration}
                onChange={(e) => setSettings({...settings, emergencyAccessMaxDuration: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-orange-500 focus:border-orange-500"
                min="1"
                max="72"
              />
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={settings.emergencyAccessRequireApproval}
                onChange={(e) => setSettings({...settings, emergencyAccessRequireApproval: e.target.checked})}
                className="h-4 w-4 text-orange-600 focus:ring-orange-500 border-gray-300 rounded"
              />
              <label className="ml-2 text-sm text-gray-700">
                Require manager approval for emergency access
              </label>
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={settings.emergencyAccessNotifyOwner}
                onChange={(e) => setSettings({...settings, emergencyAccessNotifyOwner: e.target.checked})}
                className="h-4 w-4 text-orange-600 focus:ring-orange-500 border-gray-300 rounded"
              />
              <label className="ml-2 text-sm text-gray-700">
                Notify file owner of emergency access
              </label>
            </div>
          </div>
        </div>

        {/* System Settings */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
            <Database className="h-5 w-5 mr-2 text-purple-600" />
            System Settings
          </h3>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Audit Log Retention (days)
              </label>
              <input
                type="number"
                value={settings.auditLogRetention}
                onChange={(e) => setSettings({...settings, auditLogRetention: parseInt(e.target.value)})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                min="30"
                max="365"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Backup Frequency
              </label>
              <select
                value={settings.backupFrequency}
                onChange={(e) => setSettings({...settings, backupFrequency: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
              >
                <option value="hourly">Hourly</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Maintenance Window
              </label>
              <input
                type="time"
                value={settings.maintenanceWindow}
                onChange={(e) => setSettings({...settings, maintenanceWindow: e.target.value})}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Notification Settings */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-medium text-gray-900 mb-4 flex items-center">
          <Bell className="h-5 w-5 mr-2 text-indigo-600" />
          Notification Settings
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="flex items-center">
            <input
              type="checkbox"
              checked={settings.emailNotifications}
              onChange={(e) => setSettings({...settings, emailNotifications: e.target.checked})}
              className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
            />
            <label className="ml-2 text-sm text-gray-700">
              Email Notifications
            </label>
          </div>
          
          <div className="flex items-center">
            <input
              type="checkbox"
              checked={settings.slackIntegration}
              onChange={(e) => setSettings({...settings, slackIntegration: e.target.checked})}
              className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
            />
            <label className="ml-2 text-sm text-gray-700">
              Slack Integration
            </label>
          </div>
          
          <div className="flex items-center">
            <input
              type="checkbox"
              checked={settings.smsAlerts}
              onChange={(e) => setSettings({...settings, smsAlerts: e.target.checked})}
              className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
            />
            <label className="ml-2 text-sm text-gray-700">
              SMS Alerts
            </label>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminSettings;

// project/src/app/zones/admin-zone/admin-settings/admin-settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-admin-settings',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
    FormsModule
  ],
  template: `
    <div class="settings-container">
      <!-- Header -->
      <mat-card class="header-card">
        <mat-card-content>
          <div class="header-content">
            <div class="header-info">
              <h2>System Settings</h2>
              <p>Configure system-wide settings and policies</p>
            </div>
            <div class="header-actions">
              <button mat-stroked-button>
                <mat-icon>refresh</mat-icon>
                Reset
              </button>
              <button mat-raised-button color="primary">
                <mat-icon>save</mat-icon>
                Save Changes
              </button>
            </div>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Settings Grid -->
      <div class="settings-grid">
        <!-- Security Settings -->
        <mat-card class="settings-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon>shield</mat-icon>
              Security Settings
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="settings-form">
              <mat-form-field appearance="outline">
                <mat-label>Minimum Password Length</mat-label>
                <input matInput type="number" [(ngModel)]="settings.passwordMinLength" min="6" max="20">
              </mat-form-field>

              <div class="toggle-setting">
                <mat-slide-toggle [(ngModel)]="settings.passwordRequireSpecialChars">
                  Require special characters in passwords
                </mat-slide-toggle>
              </div>

              <mat-form-field appearance="outline">
                <mat-label>Session Timeout (minutes)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.sessionTimeout" min="5" max="480">
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Max Login Attempts</mat-label>
                <input matInput type="number" [(ngModel)]="settings.maxLoginAttempts" min="3" max="10">
              </mat-form-field>
            </div>
          </mat-card-content>
        </mat-card>

        <!-- File Lock Settings -->
        <mat-card class="settings-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon>schedule</mat-icon>
              File Lock Settings
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="settings-form">
              <mat-form-field appearance="outline">
                <mat-label>Default Lock Duration (minutes)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.defaultLockDuration" min="15" max="480">
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Maximum Lock Duration (minutes)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.maxLockDuration" min="60" max="1440">
              </mat-form-field>

              <div class="toggle-setting">
                <mat-slide-toggle [(ngModel)]="settings.autoReleaseStuckLocks">
                  Auto-release stuck locks
                </mat-slide-toggle>
              </div>

              <mat-form-field appearance="outline">
                <mat-label>Stuck Lock Threshold (minutes)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.stuckLockThreshold" min="30" max="480">
              </mat-form-field>
            </div>
          </mat-card-content>
        </mat-card>

        <!-- Emergency Access Settings -->
        <mat-card class="settings-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon>warning</mat-icon>
              Emergency Access Settings
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="settings-form">
              <mat-form-field appearance="outline">
                <mat-label>Maximum Emergency Access Duration (hours)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.emergencyAccessMaxDuration" min="1" max="72">
              </mat-form-field>

              <div class="toggle-setting">
                <mat-slide-toggle [(ngModel)]="settings.emergencyAccessRequireApproval">
                  Require manager approval for emergency access
                </mat-slide-toggle>
              </div>

              <div class="toggle-setting">
                <mat-slide-toggle [(ngModel)]="settings.emergencyAccessNotifyOwner">
                  Notify file owner of emergency access
                </mat-slide-toggle>
              </div>
            </div>
          </mat-card-content>
        </mat-card>

        <!-- System Settings -->
        <mat-card class="settings-card">
          <mat-card-header>
            <mat-card-title>
              <mat-icon>storage</mat-icon>
              System Settings
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <div class="settings-form">
              <mat-form-field appearance="outline">
                <mat-label>Audit Log Retention (days)</mat-label>
                <input matInput type="number" [(ngModel)]="settings.auditLogRetention" min="30" max="365">
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Backup Frequency</mat-label>
                <mat-select [(ngModel)]="settings.backupFrequency">
                  <mat-option value="hourly">Hourly</mat-option>
                  <mat-option value="daily">Daily</mat-option>
                  <mat-option value="weekly">Weekly</mat-option>
                </mat-select>
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Maintenance Window</mat-label>
                <input matInput type="time" [(ngModel)]="settings.maintenanceWindow">
              </mat-form-field>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- Notification Settings -->
      <mat-card class="notification-card">
        <mat-card-header>
          <mat-card-title>
            <mat-icon>notifications</mat-icon>
            Notification Settings
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <div class="notification-grid">
            <div class="toggle-setting">
              <mat-slide-toggle [(ngModel)]="settings.emailNotifications">
                Email Notifications
              </mat-slide-toggle>
            </div>
            
            <div class="toggle-setting">
              <mat-slide-toggle [(ngModel)]="settings.slackIntegration">
                Slack Integration
              </mat-slide-toggle>
            </div>
            
            <div class="toggle-setting">
              <mat-slide-toggle [(ngModel)]="settings.smsAlerts">
                SMS Alerts
              </mat-slide-toggle>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .settings-container {
      display: flex;
      flex-direction: column;
      gap: 24px;
      height: 100%;
    }

    .header-content {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .header-info h2 {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      color: #111827;
    }

    .header-info p {
      margin: 4px 0 0 0;
      color: #6b7280;
      font-size: 14px;
    }

    .header-actions {
      display: flex;
      gap: 12px;
    }

    .settings-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
      gap: 24px;
    }

    .settings-card mat-card-title {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 18px;
    }

    .settings-form {
      display: flex;
      flex-direction: column;
      gap: 16px;
      margin-top: 16px;
    }

    .toggle-setting {
      display: flex;
      align-items: center;
      padding: 8px 0;
    }

    .notification-card {
      margin-top: 8px;
    }

    .notification-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin-top: 16px;
    }

    mat-form-field {
      width: 100%;
    }

    @media (max-width: 768px) {
      .settings-grid {
        grid-template-columns: 1fr;
      }
      
      .header-content {
        flex-direction: column;
        align-items: flex-start;
        gap: 16px;
      }
    }
  `]
})
export class AdminSettingsComponent {
  settings = {
    // Security Settings
    passwordMinLength: 8,
    passwordRequireSpecialChars: true,
    sessionTimeout: 30,
    maxLoginAttempts: 5,
    
    // File Lock Settings
    defaultLockDuration: 60,
    maxLockDuration: 480,
    autoReleaseStuckLocks: true,
    stuckLockThreshold: 120,
    
    // Emergency Access Settings
    emergencyAccessMaxDuration: 24,
    emergencyAccessRequireApproval: true,
    emergencyAccessNotifyOwner: true,
    
    // System Settings
    auditLogRetention: 90,
    backupFrequency: 'daily',
    maintenanceWindow: '02:00',
    
    // Notification Settings
    emailNotifications: true,
    slackIntegration: false,
    smsAlerts: false
  };
}
